import type { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

export function setupSwagger(app: INestApplication): void {
  const config = new DocumentBuilder()
    .setTitle('IArte')
    .setDescription(
      "The project was conceived as a backoffice app for an e-commerce of art goods, generated by artificial intelligence. <br/><br/>Within this theme, we have applied several resources to manage the entities of our application. <br/><br/>Thus, being possible to manage products, categories, and users. <br><br>Furthermore, we can batch update the aforementioned entities providing the user's role grants access.",
    )
    .setVersion('1.0.0')
    .addTag('Status')
    .addTag('Auth')
    .addTag('User')
    .addTag('My account')
    .addTag('Category')
    .addTag('Canva')
    .addTag('Upload')
    .addTag('Voucher')
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api', app, document);
}
